#!/bin/sh

APPDIR=$(readlink -f "$0")
APPDIR=$(dirname "$APPDIR")
java -Djna.nosys=true -Djava.library.path="$APPDIR:$APPDIR/lib" -cp "$APPDIR:$APPDIR/lib/mind_maps.jar:$APPDIR/lib/core.jar:$APPDIR/lib/jogl-all.jar:$APPDIR/lib/gluegen-rt.jar:$APPDIR/lib/jogl-all-natives-linux-armv6hf.jar:$APPDIR/lib/gluegen-rt-natives-linux-armv6hf.jar:$APPDIR/lib/apiviz-1.3.1.GA.jar:$APPDIR/lib/args4j-2.0.8.jar:$APPDIR/lib/doapamine.jar:$APPDIR/lib/toxiclibs.jar:$APPDIR/lib/umlgraph5.2.jar:$APPDIR/lib/handy.jar" mind_maps "$@"
